(()=>{
 const parent=document.querySelector('.auth-card');if(!parent)return;
 parent.insertAdjacentHTML('beforeend','<section class="sms-auth-flow" hidden><h2 data-sms-title></h2><p data-sms-description></p><form id="otp-form"><label>شماره موبایل<input name="phone" inputmode="tel" autocomplete="tel" maxlength="11" required></label><button type="button" data-otp-request>دریافت کد پیامک</button><div data-otp-code hidden><label>کد تأیید<input name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9۰-۹٠-٩]{6}"></label><label data-new-password hidden>رمز جدید<input name="password" type="password" minlength="8" maxlength="72" autocomplete="new-password"></label><button type="submit">تأیید و ادامه</button></div><p data-otp-message role="status" aria-live="polite"></p><small>کد پنج دقیقه معتبر است و حداکثر پنج تلاش دارد. مدیران با رمز وارد شوند.</small></form><button type="button" class="auth-back">بازگشت به ورود با رمز</button></section>');
 const flow=parent.querySelector('.sms-auth-flow'),form=flow.querySelector('form'),send=form.querySelector('[data-otp-request]'),panel=form.querySelector('[data-otp-code]'),out=form.querySelector('[data-otp-message]'),registration=document.querySelector('[data-form=register]'),login=document.querySelector('[data-form=login]');let mode='login',challenge='',busy=false,cooldownUntil=0,timer;
 const digits=v=>String(v).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/\s/g,'');
 function countdown(){const seconds=Math.max(0,Math.ceil((cooldownUntil-Date.now())/1000));send.disabled=busy||seconds>0;send.textContent=seconds?'ارسال مجدد پس از '+seconds+' ثانیه':challenge?'ارسال مجدد کد':'دریافت کد پیامک'}
 function show(purpose,phone=''){mode=purpose;challenge='';flow.hidden=false;document.querySelectorAll('.auth-form').forEach(f=>f.classList.remove('active'));panel.hidden=true;form.reset();form.elements.phone.value=phone;form.elements.phone.readOnly=purpose==='register';form.querySelector('[data-new-password]').hidden=purpose!=='reset';form.elements.password.required=purpose==='reset';form.elements.code.required=false;out.textContent='';flow.querySelector('[data-sms-title]').textContent={login:'ورود با کد یک‌بارمصرف',reset:'بازیابی رمز عبور',register:'تأیید شماره و ساخت حساب'}[purpose];flow.querySelector('[data-sms-description]').textContent=purpose==='register'?'کد پیامک را وارد کنید تا حساب شما ساخته شود.':'شمارهٔ حساب خود را وارد کنید تا کد تأیید ارسال شود.';flow.querySelector('.auth-back').textContent=purpose==='register'?'بازگشت و اصلاح اطلاعات ثبت‌نام':'بازگشت به ورود با رمز';countdown();form.elements.phone.focus()}
 const originalShow=showAuth;showAuth=function(type){challenge='';flow.hidden=true;originalShow(type)};document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>showAuth(b.dataset.auth));flow.querySelector('.auth-back').onclick=()=>showAuth(mode==='register'?'register':'login');
 const otpButton=document.createElement('button');otpButton.type='button';otpButton.className='otp-login-button';otpButton.textContent='ورود با کد یک‌بارمصرف';login.querySelector('.forgot-open').before(otpButton);otpButton.onclick=()=>show('login',digits(login.elements.phone.value));document.querySelector('.forgot-open').onclick=()=>show('reset',digits(login.elements.phone.value));
 async function request(payload){if(busy)return;busy=true;parent.querySelectorAll('[data-auth],.auth-back').forEach(b=>b.disabled=true);send.disabled=true;out.textContent='در حال ارسال کد…';try{if(!csrf)csrf=(await api('/csrf')).csrf;const r=await api('/auth/otp/request',{method:'POST',body:JSON.stringify(payload)});challenge=r.challenge;panel.hidden=false;form.elements.code.required=true;cooldownUntil=Date.now()+Number(r.retry_after||60)*1000;clearInterval(timer);timer=setInterval(countdown,1000);out.textContent='کد ارسال شد؛ کد دریافتی را وارد کنید.';form.elements.code.focus();return true}catch(e){out.textContent=e.message;return false}finally{busy=false;parent.querySelectorAll('[data-auth],.auth-back').forEach(b=>b.disabled=false);countdown()}}
 send.onclick=()=>{if(mode==='register'){showAuth('register');toast('برای ارسال دوباره، اطلاعات ثبت‌نام را تأیید کنید.');return}const phone=digits(form.elements.phone.value);if(!/^09\d{9}$/.test(phone)){out.textContent='شماره موبایل معتبر وارد کنید.';return}request({purpose:mode,phone})};form.elements.phone.oninput=()=>{challenge='';panel.hidden=true;form.elements.code.required=false};
 registration.onsubmit=async e=>{e.preventDefault();registration.elements.phone.value=digits(registration.elements.phone.value);if(!validate(registration))return;const button=registration.querySelector('.submit-auth');button.disabled=true;const payload={purpose:'register',name:registration.elements.name.value.trim(),phone:registration.elements.phone.value,password:registration.elements.password.value,terms:registration.querySelector('[type=checkbox]').checked};show('register',payload.phone);const accepted=await request(payload);if(accepted)registration.elements.password.value='';else{const error=out.textContent;showAuth('register');toast(error)}button.disabled=false};
 form.onsubmit=async e=>{e.preventDefault();if(!challenge||busy)return;const button=panel.querySelector('button');button.disabled=true;out.textContent='در حال تأیید…';try{const r=await api('/auth/otp/verify',{method:'POST',body:JSON.stringify({challenge,code:digits(form.elements.code.value),...(mode==='reset'?{password:form.elements.password.value}:{})})});challenge='';clearInterval(timer);form.elements.code.value=form.elements.password.value='';if(r.user.role==='admin')location.assign('admin.html');else await enterDashboard(r.user)}catch(error){out.textContent=error.message}finally{button.disabled=false}};
 const originalLogin=login.onsubmit;login.onsubmit=e=>{login.elements.phone.value=digits(login.elements.phone.value);return originalLogin(e)};
})();
