document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="site-enhancements.css">');
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),fa=n=>new Intl.NumberFormat('fa-IR').format(n||0);
const products=window.DEMO_PRODUCTS||[];
const categoryLabel={power:'پاوربانک',charger:'شارژر',audio:'صوتی',cable:'کابل',accessories:'لوازم جانبی'};
const mainNav=document.querySelector('header nav');
if(mainNav) mainNav.innerHTML='<a href="shop.html">محصولات</a><a href="#story">درباره ما</a><a href="#catalog">محصولات ویژه</a>';
const footer=document.querySelector('footer');
if(footer){footer.className='site-footer';footer.innerHTML='<div class="footer-main"><div class="footer-about"><a class="brand brand-logo" href="index.html"><img src="assets/bilumiere-logo-header.webp" alt="Gadget Land"></a><h2>تکنولوژی، ساده‌تر.</h2><p>Gadget Land مجموعه‌ای از لوازم دیجیتال و اکسسوری‌های کاربردی برای استفاده روزمره است.</p></div><div class="footer-col"><h3>محصولات</h3><a href="shop.html">همه محصولات</a><a href="shop.html?category=charger">شارژرها</a><a href="shop.html?category=cable">کابل‌ها</a><a href="shop.html?category=audio">لوازم صوتی</a></div><div class="footer-col"><h3>راهنمای خرید</h3><a href="contact.html">پشتیبانی</a><span>ارسال سریع</span><span>ضمانت کیفیت</span></div><div class="footer-col"><h3>Gadget Land</h3><a href="about.html">درباره ما</a><a href="contact.html">تماس با ما</a><span>Instagram</span></div></div><div class="footer-bottom"><span>© ۲۰۲۶ Gadget Land</span><span>دموی نمایشی فروشگاه</span></div>'}
let category='all',cart=[];try{cart=JSON.parse(localStorage.getItem('gadgetLandCart')||'[]')}catch{}
function renderProducts(){const grid=$('#products');if(!grid)return;let list=products.filter(p=>category==='all'||p.category===category),sort=$('#sort')?.value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='new')list.sort((a,b)=>b.id-a.id);grid.innerHTML=list.map(p=>`<article class="product" data-id="${p.id}"><a class="product-link" href="product.html?id=${p.id}"><div class="product-media"><img class="product-photo" src="${p.image_path}" alt="${p.name}"><span class="badge">موجود</span></div><div class="product-info"><div><h3>${p.name}</h3><small>${categoryLabel[p.category]||'لوازم دیجیتال'}</small><p>${p.description}</p></div><strong>${fa(p.price)} <small>تومان</small></strong></div></a><button class="quick">افزودن به سبد +</button></article>`).join('');$$('.quick').forEach(b=>b.onclick=()=>addToCart(+b.closest('.product').dataset.id))}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.filter;renderProducts()});$('#sort')?.addEventListener('change',renderProducts);
const drawer=$('.cart'),scrim=$('.scrim');function openCart(){drawer?.classList.add('open');scrim?.classList.add('on');document.body.classList.add('lock')}function closeCart(){drawer?.classList.remove('open');scrim?.classList.remove('on');document.body.classList.remove('lock')}$('[data-cart]')?.addEventListener('click',openCart);$('.cart-close')?.addEventListener('click',closeCart);scrim?.addEventListener('click',closeCart);
function saveCart(){localStorage.setItem('gadgetLandCart',JSON.stringify(cart));renderCart()}
function addToCart(id){const p=products.find(x=>+x.id===id);if(!p)return;const key='product-'+id,row=cart.find(x=>x.key===key);row?row.qty++:cart.push({key,id,name:p.name,price:p.price,qty:1,image_path:p.image_path});saveCart();const note=$('.toast');note?.classList.add('show');setTimeout(()=>note?.classList.remove('show'),1200)}
function renderCart(){const box=$('.cart-items'),empty=$('.cart-empty'),foot=$('.cart-foot');if(!box)return;box.innerHTML=cart.map(row=>`<div class="cart-item"><div class="cart-thumb"><img src="${row.image_path}" alt=""></div><div><h4>${row.name}</h4><small>${fa(row.price)} تومان</small><div><button data-minus="${row.key}">−</button> ${fa(row.qty)} <button data-plus="${row.key}">+</button></div></div><button data-remove="${row.key}">×</button></div>`).join('');const count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('.cart-count')&&( $('.cart-count').textContent=fa(count));$('.cart-total')&&($('.cart-total').textContent=fa(total)+' تومان');if(empty)empty.style.display=cart.length?'none':'block';if(foot)foot.style.display=cart.length?'block':'none';box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart.find(x=>x.key===b.dataset.plus).qty++;saveCart()});box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const r=cart.find(x=>x.key===b.dataset.minus);if(--r.qty<1)cart=cart.filter(x=>x!==r);saveCart()});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.remove);saveCart()})}
document.head.insertAdjacentHTML('beforeend','<style>.product-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:24px}.product{position:relative}.product-link{color:inherit;text-decoration:none}.product-media{height:auto;aspect-ratio:4/5;max-height:430px;background:#eee}.product-photo{width:100%;height:100%;object-fit:cover;display:block}.product-info{align-items:flex-start;gap:12px;padding-top:14px}.product-info h3{font-size:14px}.product-info p{font-size:10px;line-height:1.7;color:#666;margin:7px 0 0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.product-info strong{white-space:nowrap;font-size:13px}.quick{position:static;width:100%;transform:none;margin-top:5px}@media(max-width:1000px){.product-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.product-grid{grid-template-columns:repeat(2,1fr);gap:12px}}</style>');
renderProducts();renderCart();
const loader=$('.loader'),loaderNumber=loader?.querySelector('b');if(loader&&loaderNumber){let progress=0;const loading=setInterval(()=>{progress=Math.min(100,progress+20);loaderNumber.textContent=fa(progress);if(progress===100){clearInterval(loading);loader.classList.add('done')}},50)}
