document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="site-enhancements.css">');
const mainNav=document.querySelector('header nav');
if(mainNav) mainNav.innerHTML='<a class="mega-trigger" href="shop.html">رایحه‌ها <span>⌄</span></a><div class="mega-menu"><div class="mega-feature"><span>OLFACTIVE COLLECTION 2026</span><b>رایحه‌ای برای امضای تو</b><a href="shop.html">مشاهده همه عطرها ←</a></div><div><h4>دسته‌بندی عطرها</h4><a href="shop.html?category=women">زنانه</a><a href="shop.html?category=men">مردانه</a><a href="shop.html?category=unisex">یونی‌سکس</a><a href="shop.html?category=niche">نیش</a></div><div><h4>درباره bilumiere</h4><a href="about.html">درباره ما</a><a href="contact.html">تماس با ما</a></div></div><a href="about.html">درباره ما</a><a href="contact.html">تماس با ما</a>';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),fa=n=>new Intl.NumberFormat('fa-IR').format(n||0),grid=$('#products');
let products=window.DEMO_PRODUCTS||[],category='all',cart=[];try{cart=JSON.parse(localStorage.getItem('nouraCart')||'[]')}catch{}
const labels={women:'زنانه',men:'مردانه',unisex:'یونی‌سکس',niche:'نیش'};
function renderProducts(){if(!grid)return;let list=products.filter(p=>category==='all'||p.category===category),sort=$('#sort')?.value||'new';if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);grid.innerHTML=list.map(p=>`<article class="product"><a class="product-link" href="product.html?id=${p.id}"><div class="product-media"><img class="product-photo" src="${p.image_path}" alt="${p.name}"><span class="badge">موجود</span></div><div class="product-info"><div><h3>${p.name}</h3><small>${labels[p.category]}</small><p>${p.description}</p></div><strong>${fa(p.price)} <small>تومان</small></strong></div></a><button class="quick">افزودن به سبد +</button></article>`).join('');$$('.quick').forEach((b,i)=>b.onclick=()=>addToCart(list[i].id))}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.filter;renderProducts()});if($('#sort'))$('#sort').onchange=renderProducts;
function saveCart(){localStorage.setItem('nouraCart',JSON.stringify(cart));localStorage.setItem('nouraCartCount',String(cart.reduce((s,x)=>s+x.qty,0)))}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const row=cart.find(x=>x.key==='product-'+id);row?row.qty++:cart.push({key:'product-'+id,id:p.id,variant_id:p.id,name:p.name,price:p.price,qty:1,image_path:p.image_path});saveCart();renderCart();const note=$('.toast');if(note){note.textContent='عطر به سبد اضافه شد';note.classList.add('show');setTimeout(()=>note.classList.remove('show'),1500)}}
const drawer=$('.cart'),scrim=$('.scrim');function openCart(){drawer?.classList.add('open');scrim?.classList.add('on');document.body.classList.add('lock')}function closeCart(){drawer?.classList.remove('open');scrim?.classList.remove('on');document.body.classList.remove('lock')}$('[data-cart]')?.addEventListener('click',openCart);$('.cart-close')?.addEventListener('click',closeCart);scrim?.addEventListener('click',closeCart);
function renderCart(){const box=$('.cart-items'),empty=$('.cart-empty'),foot=$('.cart-foot');if(!box)return;box.innerHTML=cart.map(row=>`<div class="cart-item"><div class="cart-thumb"><img src="${row.image_path}" alt=""></div><div><h4>${row.name}</h4><small>${fa(row.price)} تومان</small><div><button data-minus="${row.key}">−</button> ${fa(row.qty)} <button data-plus="${row.key}">+</button></div></div><button data-remove="${row.key}">×</button></div>`).join('');$('.cart-count')&&( $('.cart-count').textContent=fa(cart.reduce((s,x)=>s+x.qty,0)));$('.cart-total')&&( $('.cart-total').textContent=fa(cart.reduce((s,x)=>s+x.price*x.qty,0))+' تومان');if(empty)empty.style.display=cart.length?'none':'block';if(foot)foot.style.display=cart.length?'block':'none';box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart.find(x=>x.key===b.dataset.plus).qty++;saveCart();renderCart()});box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{let r=cart.find(x=>x.key===b.dataset.minus);if(--r.qty<1)cart=cart.filter(x=>x!==r);saveCart();renderCart()});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.remove);saveCart();renderCart()})}
renderProducts();renderCart();
