(function(){
if(document.querySelector('.jewelry-overlay'))return;const canvas=document.createElement('canvas'),halo=document.createElement('div'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;canvas.className='jewelry-overlay';canvas.setAttribute('aria-hidden','true');halo.className='jewelry-overlay-vignette';document.body.append(canvas,halo);let w,h,dpr,items=[],pointer={x:-9999,y:-9999},last=0;
const colors=['255,128,137','136,198,255','255,221,112','190,165,255','255,255,255'];const rand=(a,b)=>a+Math.random()*(b-a);
function make(initial=true,i=0){const depth=rand(.55,1.25);return{x:rand(-40,w+40),y:initial?rand(-h*.1,h):rand(-160,-25),size:rand(5,13)*depth,vy:rand(.16,.42)*depth,vx:rand(-.08,.08),sway:rand(.0012,.003),phase:rand(0,Math.PI*2),rot:rand(0,Math.PI*2),vr:rand(-.0018,.0018),type:i%4,color:colors[i%colors.length],depth}}
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,w<700?1.15:1.6);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const count=reduced?6:w<700?11:20;items=Array.from({length:count},(_,i)=>make(true,i))}
function pearl(p){const g=ctx.createRadialGradient(-p.size*.28,-p.size*.32,1,0,0,p.size);g.addColorStop(0,'rgba(255,255,255,.98)');g.addColorStop(.25,`rgba(${p.color},.92)`);g.addColorStop(.72,`rgba(${p.color},.55)`);g.addColorStop(1,'rgba(70,66,92,.28)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,p.size*.62,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=.7;ctx.stroke()}
function crystal(p){const g=ctx.createLinearGradient(-p.size,-p.size,p.size,p.size);g.addColorStop(0,'rgba(255,255,255,.96)');g.addColorStop(.34,`rgba(${p.color},.82)`);g.addColorStop(.68,'rgba(255,255,255,.45)');g.addColorStop(1,'rgba(70,79,113,.5)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,-p.size);ctx.lineTo(p.size*.68,-p.size*.18);ctx.lineTo(p.size*.34,p.size);ctx.lineTo(-p.size*.68,p.size*.45);ctx.lineTo(-p.size*.52,-p.size*.36);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.82)';ctx.lineWidth=.8;ctx.stroke();ctx.beginPath();ctx.moveTo(0,-p.size);ctx.lineTo(p.size*.08,p.size*.28);ctx.lineTo(p.size*.68,-p.size*.18);ctx.moveTo(p.size*.08,p.size*.28);ctx.lineTo(-p.size*.68,p.size*.45);ctx.stroke()}
function ring(p){ctx.strokeStyle=`rgba(${p.color},.8)`;ctx.lineWidth=Math.max(1.4,p.size*.18);ctx.beginPath();ctx.ellipse(0,0,p.size,p.size*.52,.22,0,Math.PI*1.72);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=.65;ctx.beginPath();ctx.ellipse(-1,-1,p.size*.82,p.size*.4,.22,.1,Math.PI*1.25);ctx.stroke()}
function sparkle(p){ctx.strokeStyle=`rgba(${p.color},.92)`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-p.size,0);ctx.quadraticCurveTo(0,0,p.size,0);ctx.moveTo(0,-p.size);ctx.quadraticCurveTo(0,0,0,p.size);ctx.stroke();ctx.fillStyle='rgba(255,255,255,.95)';ctx.beginPath();ctx.arc(0,0,1.4,0,Math.PI*2);ctx.fill()}
function draw(now){if(document.hidden)return requestAnimationFrame(draw);if(now-last<28&&!reduced)return requestAnimationFrame(draw);const dt=Math.min(40,now-last||16);last=now;ctx.clearRect(0,0,w,h);items.forEach((p,i)=>{if(!reduced){p.y+=p.vy*dt;p.x+=(p.vx+Math.sin(now*p.sway+p.phase)*.045)*dt;p.rot+=p.vr*dt;if(p.y>h+60||p.x>w+80||p.x<-80)Object.assign(p,make(false,i))}const dx=p.x-pointer.x,dy=p.y-pointer.y,dist=Math.hypot(dx,dy);if(dist<120&&!reduced){p.x+=dx/(dist||1)*(120-dist)*.015;p.y+=dy/(dist||1)*(120-dist)*.015}ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.globalAlpha=.56+p.depth*.26;ctx.shadowColor=`rgba(${p.color},.55)`;ctx.shadowBlur=8*p.depth;[pearl,crystal,ring,sparkle][p.type](p);ctx.restore()});if(!reduced)requestAnimationFrame(draw)}
addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;halo.style.setProperty('--light-x',e.clientX/innerWidth*100+'%');halo.style.setProperty('--light-y',e.clientY/innerHeight*100+'%')},{passive:true});addEventListener('pointerleave',()=>pointer={x:-9999,y:-9999},{passive:true});addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!reduced){last=performance.now();requestAnimationFrame(draw)}});resize();draw(0);
})();
