const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),fa=n=>new Intl.NumberFormat('fa-IR').format(n||0),labels={women:'زنانه',men:'مردانه',unisex:'یونی‌سکس',niche:'نیش',ring:'زنانه',necklace:'مردانه',bracelet:'یونی‌سکس',earring:'نیش'};let variants=[],selected=null,allProducts=[],csrf='',currentUser=null;
function notice(text){const n=$('.notice');n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
function cartCount(){let cart=[];try{cart=JSON.parse(localStorage.getItem('nouraCart')||'[]')}catch{}$('.cart-count').textContent=fa(cart.reduce((sum,row)=>sum+row.qty,0))}
function updateVariant(){selected=variants.find(v=>String(v.variant_id)===$('.variant-select').value)||variants[0];if(!selected)return;$('.price').innerHTML=`${fa(selected.price)} <small>تومان</small>`;$('.selected-sku').textContent='SKU: '+selected.sku;$('.meta-sku').textContent=selected.sku;$('.selected-stock').textContent=fa(selected.stock)+' عدد موجود';$('.stock-text').textContent=+selected.stock?'آماده ارسال — موجود در انبار':'در حال حاضر ناموجود';$('.availability').classList.toggle('out',!+selected.stock);$('.add-product').disabled=!+selected.stock;$('.qty').value=1;$('.qty').max=selected.stock}
function addToCart(){if(!selected||!+selected.stock)return;const qty=Math.min(+selected.stock,Math.max(1,parseInt($('.qty').value)||1));let cart=[];try{cart=JSON.parse(localStorage.getItem('nouraCart')||'[]')}catch{}const key=`variant-${selected.variant_id}`,row=cart.find(x=>x.key===key);if(row)row.qty=Math.min(+selected.stock,row.qty+qty);else cart.push({key,id:+selected.id,variant_id:+selected.variant_id,name:selected.name,price:+selected.price,qty,color:selected.color||'default',colorLabel:selected.color||'نسخه اصلی',size:selected.size,image_path:selected.image_path});localStorage.setItem('nouraCart',JSON.stringify(cart));localStorage.setItem('nouraCartCount',String(cart.reduce((s,x)=>s+x.qty,0)));cartCount();notice('عطر به سبد خرید اضافه شد.')}
function renderRelated(current){const list=allProducts.filter(p=>+p.id!==+current.id).slice(0,4);$('.related-grid').innerHTML=list.map(p=>`<a class="related-card" href="product.html?id=${p.id}"><figure>${p.image_path?`<img src="${p.image_path}" alt="${p.name}">`:''}</figure><h3>${p.name}</h3><span>${fa(p.price)} تومان</span></a>`).join('')||'<p>عطر مرتبط دیگری وجود ندارد.</p>'}
function render(product,catalog){document.title=product.name+' — bilumiere';$('.wishlist').dataset.productFavorite=product.id;document.querySelector('meta[name="description"]').content=product.description||product.name;$('.crumb-category').textContent=labels[product.category]||'عطر';$('.crumb-name').textContent=product.name;$('.product-name').textContent=product.name;$('.short-description').textContent=product.description||'رایحه‌ای ماندگار از انتخاب‌های bilumiere؛ مناسب استفاده روزمره و هدیه.';$('.full-description').textContent=product.description||'این عطر از انتخاب‌های bilumiere با تمرکز بر کیفیت رایحه، ماندگاری و تجربه استفاده انتخاب شده است. اصالت و سلامت آن پیش از ارسال کنترل و در بسته‌بندی اختصاصی bilumiere ارائه می‌شود.';$('.meta-category').textContent=labels[product.category]||product.category;$('.meta-category').href='shop.html?category='+product.category;
 const image=product.image_path;if(image){$('.gallery-stage').innerHTML=`<img src="${image}" alt="${product.name}"><button class="zoom" aria-label="نمایش بزرگ">⌕</button>`;$('.thumbnails').innerHTML=`<button class="thumb"><img src="${image}" alt="نمای محصول"></button>`;$('.gallery-stage img').onclick=openLightbox;$('.zoom').onclick=openLightbox}else{$('.gallery-stage').innerHTML='<div class="fallback"><i></i><span>تصویر عطر</span></div>'}
 $('.variant-select').innerHTML=variants.map((v,i)=>`<option value="${v.variant_id}">${v.size?'حجم '+v.size:'نسخه اصلی'}${v.color&&v.color!=='default'?' — '+v.color:''}${i===0?'':''}</option>`).join('');$('.variation-box').style.display=variants.length>1?'block':'none';$('.variant-select').onchange=updateVariant;
 $('.spec-list').innerHTML=[['برند',product.brand||'—'],['دسته بندی',labels[product.category]||product.category],['کد محصول',product.sku],['نسخه / غلظت',product.color==='default'?'نسخه اصلی':product.color],['حجم',product.size||'حجم اصلی'],...((catalog?.attributes||[]).filter(x=>+x.visible).map(x=>[x.attribute_name,x.value||x.custom_value])),['وضعیت',+product.stock?'موجود':'ناموجود'],['بسته بندی','جعبه اختصاصی bilumiere']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');updateVariant();renderRelated(product)}
function openLightbox(){if(!variants[0]||!$('.gallery-stage img'))return;$('.lightbox img').src=$('.gallery-stage img').src;$('.lightbox').classList.add('open')}
async function init(){const id=new URLSearchParams(location.search).get('id');if(!id){location.replace('shop.html');return}try{const [detail,list,extras,catalogResult,session]=await Promise.all([fetch('api/products/'+encodeURIComponent(id)).then(r=>r.json()),fetch('api/products').then(r=>r.json()),fetch('api/products/'+encodeURIComponent(id)+'/extras').then(r=>r.json()),fetch('api/products/'+encodeURIComponent(id)+'/catalog').then(r=>r.json()),fetch('api/csrf',{credentials:'same-origin'}).then(r=>r.json())]);if(!detail.ok)throw new Error();csrf=session.csrf;currentUser=session.user;variants=detail.product;allProducts=list.products||[];render(variants[0],catalogResult.catalog);if(variants[0].long_description)$('.full-description').textContent=variants[0].long_description;const images=[variants[0].image_path,...extras.images.map(x=>x.path)].filter((x,i,a)=>x&&a.indexOf(x)===i);if(images.length){$('.thumbnails').innerHTML=images.map((src,i)=>`<button class="thumb ${i?'':'active'}" data-image="${src}"><img src="${src}" alt="نمای محصول"></button>`).join('');$$('[data-image]').forEach(b=>b.onclick=()=>{$('.gallery-stage img').src=b.dataset.image;$$('.thumb').forEach(x=>x.classList.toggle('active',x===b))})}renderProductReviews(extras.reviews||[],id)}catch{$('main').innerHTML='<div class="error-page"><h1>محصول پیدا نشد</h1><a href="shop.html">بازگشت به فروشگاه</a></div>'}}
$('.qty-plus').onclick=()=>{if(selected)$('.qty').value=Math.min(+selected.stock,(parseInt($('.qty').value)||1)+1)};$('.qty-minus').onclick=()=>$('.qty').value=Math.max(1,(parseInt($('.qty').value)||1)-1);$('.qty').onchange=()=>{$('.qty').value=Math.min(+selected.stock,Math.max(1,parseInt($('.qty').value)||1))};$('.add-product').onclick=addToCart;$('.share').onclick=async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);notice('لینک محصول کپی شد.')}}catch{}};$$('[data-tab]').forEach(button=>button.onclick=()=>{$$('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===button.dataset.tab))});$('.lightbox button').onclick=()=>$('.lightbox').classList.remove('open');$('.lightbox').onclick=e=>{if(e.target===$('.lightbox'))$('.lightbox').classList.remove('open')};cartCount();init();
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="custom-select.css?v=1">');const sharedSelectScript=document.createElement('script');sharedSelectScript.src='custom-select.js?v=8';sharedSelectScript.defer=true;document.body.appendChild(sharedSelectScript);
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="product-title-fix.css?v=1">');const adaptiveProductTitle=document.querySelector('.product-name');if(adaptiveProductTitle){const resizeProductTitle=()=>{const length=Array.from(adaptiveProductTitle.textContent.replace(/\s+/g,'')).length;adaptiveProductTitle.classList.toggle('is-long',length>42);adaptiveProductTitle.classList.toggle('is-very-long',length>70)};new MutationObserver(resizeProductTitle).observe(adaptiveProductTitle,{childList:true,characterData:true,subtree:true});resizeProductTitle()}
