const fa=n=>new Intl.NumberFormat('fa-IR').format(n);
const variants={ice:{label:'آبی یخی',gem:['#effbff','#77bfe8'],sizes:{52:{price:4280000,stock:2},54:{price:4280000,stock:3},56:{price:4390000,stock:0},58:{price:4390000,stock:1}}},coral:{label:'مرجانی',gem:['#ffe9e4','#eb7770'],sizes:{52:{price:4480000,stock:0},54:{price:4480000,stock:4},56:{price:4590000,stock:2},58:{price:4590000,stock:0}}},lemon:{label:'لیمویی',gem:['#fffbd9','#e7c33f'],sizes:{52:{price:4480000,stock:1},54:{price:4480000,stock:0},56:{price:4590000,stock:5},58:{price:4590000,stock:2}}}};
let color='ice',size=54;
const price=document.querySelector('[data-price]'),buttonPrice=document.querySelector('[data-button-price]'),stockText=document.querySelector('[data-stock]'),sku=document.querySelector('[data-sku]'),addButton=document.querySelector('.add-product');
function updateVariant(){const variant=variants[color],selected=variant.sizes[size];document.querySelector('[data-color-label]').textContent=variant.label;price.innerHTML=`${fa(selected.price)} <small>تومان</small>`;buttonPrice.textContent=`${fa(selected.price)} تومان`;sku.textContent=`SKU: NR-AQ-${color.toUpperCase()}-${size}`;stockText.textContent=selected.stock?(selected.stock<4?`تنها ${fa(selected.stock)} عدد باقی مانده`:'آماده‌ی ارسال'):'این ترکیب فعلاً ناموجود است';addButton.disabled=!selected.stock;addButton.querySelector('span').textContent=selected.stock?'افزودن به سبد':'ناموجود';document.querySelector('.stock').classList.toggle('out',!selected.stock);document.querySelectorAll('.sizes button').forEach(button=>{const buttonSize=Number(button.dataset.size);button.disabled=!variant.sizes[buttonSize].stock;button.classList.toggle('active',buttonSize===size)})}
document.querySelectorAll('.colors button').forEach(button=>button.addEventListener('click',()=>{color=button.dataset.color;document.querySelectorAll('.colors button').forEach(item=>item.classList.toggle('active',item===button));if(!variants[color].sizes[size].stock)size=Number(Object.entries(variants[color].sizes).find(([,item])=>item.stock)[0]);updateVariant()}));
document.querySelectorAll('.sizes button').forEach(button=>button.addEventListener('click',()=>{size=Number(button.dataset.size);updateVariant()}));

const canvas=document.querySelector('#ring-viewer'),ctx=canvas.getContext('2d');let width=0,height=0,rotation=-.35,targetRotation=-.35,zoom=1,targetZoom=1,dragging=false,lastX=0;
function resizeCanvas(){const dpr=Math.min(devicePixelRatio,2),rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function ringPath(rx,ry){ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.stroke()}
function drawRing(){rotation+=(targetRotation-rotation)*.08;zoom+=(targetZoom-zoom)*.1;ctx.clearRect(0,0,width,height);const radius=Math.min(width,height)*.27*zoom,flatness=.28+.7*Math.abs(Math.cos(rotation));ctx.save();ctx.translate(width*.5,height*.52);ctx.rotate(Math.sin(rotation)*.18);const shadow=ctx.createRadialGradient(0,radius*.65,0,0,radius*.65,radius*1.2);shadow.addColorStop(0,'rgba(60,66,95,.2)');shadow.addColorStop(1,'transparent');ctx.fillStyle=shadow;ctx.fillRect(-radius*1.5,-radius*.2,radius*3,radius*1.7);ctx.lineWidth=radius*.16;const metal=ctx.createLinearGradient(-radius,-radius,radius,radius);metal.addColorStop(0,'#84909d');metal.addColorStop(.22,'#fff');metal.addColorStop(.48,'#aab2ba');metal.addColorStop(.72,'#fff');metal.addColorStop(1,'#707b88');ctx.strokeStyle=metal;ctx.shadowColor='rgba(55,67,95,.24)';ctx.shadowBlur=25;ringPath(radius,radius*flatness);ctx.shadowBlur=0;ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.9)';ringPath(radius*.94,radius*flatness*.9);const gemX=radius*Math.sin(rotation)*.56,gemY=-radius*flatness*.94,gemRadius=radius*.25,gem=ctx.createRadialGradient(gemX-gemRadius*.3,gemY-gemRadius*.35,2,gemX,gemY,gemRadius);gem.addColorStop(0,'#fff');gem.addColorStop(.3,variants[color].gem[0]);gem.addColorStop(1,variants[color].gem[1]);ctx.fillStyle=gem;ctx.beginPath();for(let i=0;i<12;i++){const angle=i/12*Math.PI*2,pointRadius=i%2?gemRadius*.83:gemRadius;ctx.lineTo(gemX+Math.cos(angle)*pointRadius,gemY+Math.sin(angle)*pointRadius)}ctx.closePath();ctx.fill();ctx.strokeStyle='#f8fbff';ctx.lineWidth=5;ctx.stroke();ctx.restore();requestAnimationFrame(drawRing)}
resizeCanvas();addEventListener('resize',resizeCanvas);drawRing();canvas.addEventListener('pointerdown',event=>{dragging=true;lastX=event.clientX;canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointermove',event=>{if(dragging){targetRotation+=(event.clientX-lastX)*.012;lastX=event.clientX}});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('wheel',event=>{event.preventDefault();targetZoom=Math.max(.72,Math.min(1.5,targetZoom-event.deltaY*.001))},{passive:false});
function setView(view){document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));document.querySelector('.stage-photo').classList.toggle('show',view==='photo');document.querySelector('.stage-macro').classList.toggle('show',view==='macro');canvas.style.opacity=view==='3d'?'1':'0';document.querySelector('.drag-hint').style.opacity=view==='3d'?'1':'0'}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
const modal=document.querySelector('.size-modal');function closeGuide(){modal.classList.remove('open');document.body.classList.remove('lock')}document.querySelector('.size-guide-open').addEventListener('click',()=>{modal.classList.add('open');document.body.classList.add('lock')});document.querySelector('.size-guide-close').addEventListener('click',closeGuide);document.querySelector('.use-size').addEventListener('click',closeGuide);modal.addEventListener('click',event=>{if(event.target===modal)closeGuide()});addEventListener('keydown',event=>{if(event.key==='Escape')closeGuide()});
function readCart(){try{return JSON.parse(localStorage.getItem('nouraCart')||'[]')}catch{return[]}}function updateCartCount(){document.querySelector('.cart-count').textContent=fa(readCart().reduce((sum,item)=>sum+item.qty,0))}
addButton.addEventListener('click',()=>{if(addButton.disabled)return;const cart=readCart(),key=`akoya-${color}-${size}`,existing=cart.find(item=>item.key===key);if(existing)existing.qty+=1;else cart.push({key,id:1,name:'انگشتر آکویا',color,colorLabel:variants[color].label,size,price:variants[color].sizes[size].price,qty:1});localStorage.setItem('nouraCart',JSON.stringify(cart));localStorage.setItem('nouraCartCount',String(cart.reduce((sum,item)=>sum+item.qty,0)));updateCartCount();const toast=document.querySelector('.pdp-toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});
const cursor=document.querySelector('.cursor');let mouseX=innerWidth/2,mouseY=innerHeight/2,cursorX=mouseX,cursorY=mouseY;addEventListener('pointermove',event=>{mouseX=event.clientX;mouseY=event.clientY});function cursorLoop(){cursorX+=(mouseX-cursorX)*.16;cursorY+=(mouseY-cursorY)*.16;cursor.style.transform=`translate3d(${cursorX-16}px,${cursorY-16}px,0)`;requestAnimationFrame(cursorLoop)}cursorLoop();updateVariant();updateCartCount();
