CREATE TABLE IF NOT EXISTS admin_order_hidden(order_id BIGINT UNSIGNED PRIMARY KEY,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_address_saved(order_id BIGINT UNSIGNED PRIMARY KEY,address_id BIGINT UNSIGNED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
