<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
require __DIR__.'/PaymentGateway.php';
require __DIR__.'/SmsGateway.php';
require __DIR__.'/integrations.php';

try {
    $path=route();$method=$_SERVER['REQUEST_METHOD'];integrationRoutes($path,$method);
    if($path==='/health')respond(['ok'=>true,'service'=>'bilumiere-api','time'=>gmdate('c')]);
    if($path==='/csrf'){$sessionUser=user();if($sessionUser)$sessionUser=requireUser();respond(['ok'=>true,'csrf'=>csrfToken(),'user'=>$sessionUser]);}
    if($path==='/settings/public'&&$method==='GET'){$settings=settingsMap();$storeName=$settings['store_name']??'bilumiere';if(strtolower($storeName)==='noura')$storeName='bilumiere';respond(['ok'=>true,'settings'=>['store_name'=>$storeName,'support_phone'=>$settings['support_phone']??'','standard_shipping'=>(int)($settings['standard_shipping']??0),'express_shipping'=>(int)($settings['express_shipping']??120000),'return_days'=>(int)($settings['return_days']??7)]]);}
    if($path==='/auth/login'&&$method==='POST'){
        requireCsrf();$d=jsonBody();$phone=cleanPhone((string)($d['phone']??''));$stmt=db()->prepare('SELECT id,name,phone,password_hash,role,active FROM users WHERE phone=? LIMIT 1');$stmt->execute([$phone]);$row=$stmt->fetch();
        if(!$row||!$row['active']||!password_verify((string)($d['password']??''),$row['password_hash']))fail('شماره موبایل یا رمز عبور نادرست است.',401);
        session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$row['id'],'name'=>$row['name'],'phone'=>$row['phone'],'role'=>$row['role']];audit('login','user',(int)$row['id']);respond(['ok'=>true,'user'=>$_SESSION['user']]);
    }
    if($path==='/auth/logout'&&$method==='POST'){requireCsrf();$_SESSION=[];session_destroy();respond(['ok'=>true]);}
    if($path==='/products'&&$method==='GET'){$rows=db()->query('SELECT p.id,p.name,p.slug,p.description,p.image_path,CASE WHEN LOWER(p.brand)="noura" THEN "bilumiere" ELSE p.brand END brand,p.category,MIN(v.id) variant_id,MIN(v.price) price,SUM(v.stock) stock,(SELECT COALESCE(SUM(oi.quantity),0) FROM order_items oi WHERE oi.product_id=p.id) sales_count FROM products p JOIN product_variants v ON v.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY p.created_at DESC')->fetchAll();respond(['ok'=>true,'products'=>$rows]);}
    if(preg_match('#^/products/(\d+)$#',$path,$m)&&$method==='GET'){$stmt=db()->prepare('SELECT p.id,p.name,p.slug,p.description,p.long_description,p.image_path,CASE WHEN LOWER(p.brand)="noura" THEN "bilumiere" ELSE p.brand END brand,p.category,v.id variant_id,v.sku,v.color,v.size,v.price,v.stock FROM products p JOIN product_variants v ON v.product_id=p.id WHERE p.id=? AND p.active=1');$stmt->execute([(int)$m[1]]);$rows=$stmt->fetchAll();if(!$rows)fail('محصول پیدا نشد.',404);respond(['ok'=>true,'product'=>$rows]);}
    if(preg_match('#^/products/(\d+)/extras$#',$path,$m)&&$method==='GET'){$id=(int)$m[1];$images=db()->prepare('SELECT id,path,sort_order FROM product_images WHERE product_id=? ORDER BY sort_order,id');$images->execute([$id]);$reviews=db()->prepare('SELECT r.id,r.rating,r.body,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? AND r.approved=1 AND NOT EXISTS(SELECT 1 FROM review_rejections x WHERE x.review_id=r.id) ORDER BY r.created_at DESC');$reviews->execute([$id]);respond(['ok'=>true,'images'=>$images->fetchAll(),'reviews'=>$reviews->fetchAll()]);}
    if(preg_match('#^/products/(\d+)/reviews$#',$path,$m)&&$method==='POST'){requireCsrf();$u=requireUser();$d=jsonBody();$rating=(int)($d['rating']??0);$body=trim((string)($d['body']??''));if($rating<1||$rating>5||mb_strlen($body)<3||mb_strlen($body)>2000)fail('امتیاز و متن دیدگاه را کامل کنید.',422);db()->prepare('INSERT INTO reviews(user_id,product_id,rating,body,approved)VALUES(?,?,?,?,0) ON DUPLICATE KEY UPDATE rating=VALUES(rating),body=VALUES(body),approved=0,created_at=CURRENT_TIMESTAMP')->execute([$u['id'],(int)$m[1],$rating,$body]);respond(['ok'=>true]);}
    if($path==='/account/profile'&&$method==='PATCH'){requireCsrf();$u=requireUser();$d=jsonBody();$name=trim((string)($d['name']??''));if(mb_strlen($name)<2)fail('نام معتبر نیست.',422);db()->prepare('UPDATE users SET name=? WHERE id=?')->execute([$name,$u['id']]);$_SESSION['user']['name']=$name;respond(['ok'=>true,'user'=>$_SESSION['user']]);}
    if($path==='/account/password'&&$method==='PATCH'){requireCsrf();$u=requireUser();$d=jsonBody();$current=(string)($d['current_password']??'');$password=(string)($d['new_password']??'');if(strlen($password)<8)fail('رمز جدید باید حداقل ۸ کاراکتر باشد.',422);$s=db()->prepare('SELECT password_hash FROM users WHERE id=?');$s->execute([$u['id']]);if(!password_verify($current,(string)$s->fetchColumn()))fail('رمز فعلی نادرست است.',422);db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$u['id']]);audit('password_changed','user',(int)$u['id']);respond(['ok'=>true]);}
    if($path==='/account/addresses'&&$method==='GET'){$u=requireUser();$s=db()->prepare('SELECT * FROM addresses WHERE user_id=? ORDER BY id DESC');$s->execute([$u['id']]);respond(['ok'=>true,'addresses'=>$s->fetchAll()]);}
    if($path==='/account/addresses'&&$method==='POST'){requireCsrf();$u=requireUser();$d=jsonBody();foreach(['title','recipient','phone','province','city','address','postal_code'] as $f)if(trim((string)($d[$f]??''))==='')fail('اطلاعات آدرس کامل نیست.',422);db()->prepare('INSERT INTO addresses(user_id,title,recipient,phone,province,city,address,postal_code)VALUES(?,?,?,?,?,?,?,?)')->execute([$u['id'],$d['title'],$d['recipient'],$d['phone'],$d['province'],$d['city'],$d['address'],$d['postal_code']]);respond(['ok'=>true,'id'=>(int)db()->lastInsertId()],201);}
    if(preg_match('#^/account/addresses/(\d+)$#',$path,$m)&&$method==='DELETE'){requireCsrf();$u=requireUser();db()->prepare('DELETE FROM addresses WHERE id=? AND user_id=?')->execute([(int)$m[1],$u['id']]);respond(['ok'=>true]);}
    if($path==='/account/favorites'&&$method==='GET'){$u=requireUser();$s=db()->prepare('SELECT p.id,p.name,p.image_path,(SELECT MIN(v.price) FROM product_variants v WHERE v.product_id=p.id) price FROM favorites f JOIN products p ON p.id=f.product_id WHERE f.user_id=? AND p.active=1 ORDER BY f.created_at DESC,p.id DESC');$s->execute([$u['id']]);respond(['ok'=>true,'favorites'=>$s->fetchAll()]);}
    if(preg_match('#^/account/favorites/(\d+)$#',$path,$m)&&$method==='POST'){requireCsrf();$u=requireUser();db()->prepare('INSERT IGNORE INTO favorites(user_id,product_id)VALUES(?,?)')->execute([$u['id'],(int)$m[1]]);respond(['ok'=>true]);}
    if(preg_match('#^/account/favorites/(\d+)$#',$path,$m)&&$method==='DELETE'){requireCsrf();$u=requireUser();db()->prepare('DELETE FROM favorites WHERE user_id=? AND product_id=?')->execute([$u['id'],(int)$m[1]]);respond(['ok'=>true]);}
    if($path==='/coupons/validate'&&$method==='POST'){$d=jsonBody();$code=strtoupper(trim((string)($d['code']??'')));$subtotal=(int)($d['subtotal']??0);$s=db()->prepare('SELECT type,value,min_order FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>NOW())');$s->execute([$code]);$c=$s->fetch();if(!$c||$subtotal<(int)$c['min_order'])fail('کد تخفیف معتبر نیست.',422);$discount=$c['type']==='percent'?intdiv($subtotal*(int)$c['value'],100):min($subtotal,(int)$c['value']);respond(['ok'=>true,'discount'=>$discount,'code'=>$code]);}
    if($path==='/orders'&&$method==='GET'){$current=requireUser();$stmt=db()->prepare('SELECT o.id,o.order_number,o.status,o.payment_status,o.total,o.created_at,(SELECT COALESCE(SUM(oi.quantity),0) FROM order_items oi WHERE oi.order_id=o.id) items_count FROM orders o WHERE o.user_id=? ORDER BY o.created_at DESC');$stmt->execute([$current['id']]);respond(['ok'=>true,'orders'=>$stmt->fetchAll()]);}
    if(preg_match('#^/orders/(\d+)$#',$path,$m)&&$method==='GET'){$current=requireUser();$s=db()->prepare('SELECT id,order_number,status,payment_status,subtotal,shipping,discount,total,shipping_address,created_at FROM orders WHERE id=? AND user_id=?');$s->execute([(int)$m[1],$current['id']]);$order=$s->fetch();if(!$order)fail('سفارش پیدا نشد.',404);$items=db()->prepare('SELECT oi.product_id,oi.sku,oi.unit_price,oi.quantity,p.name,p.image_path FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?');$items->execute([(int)$m[1]]);$order['items']=$items->fetchAll();respond(['ok'=>true,'order'=>$order]);}
    if($path==='/orders'&&$method==='POST'){
        requireCsrf();$current=requireUser();$d=jsonBody();$items=$d['items']??[];if(!$items)fail('سبد خرید خالی است.',422);$pdo=db();$pdo->beginTransaction();
        try{$subtotal=0;$locked=[];foreach($items as $item){$variantId=(int)($item['variant_id']??0);$qty=max(1,(int)($item['qty']??1));$stmt=$pdo->prepare('SELECT id,product_id,sku,price,stock FROM product_variants WHERE id=? FOR UPDATE');$stmt->execute([$variantId]);$variant=$stmt->fetch();if(!$variant||$variant['stock']<$qty)throw new DomainException('موجودی یکی از محصولات کافی نیست.');$subtotal+=(int)$variant['price']*$qty;$locked[]=[$variant,$qty];}
            $shopSettings=settingsMap();$delivery='standard';$shipping=max(0,(int)($shopSettings['standard_shipping']??0));$discount=0;$couponCode=strtoupper(trim((string)($d['coupon']??'')));if($couponCode){$coupon=$pdo->prepare('SELECT type,value,min_order FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>NOW())');$coupon->execute([$couponCode]);$coupon=$coupon->fetch();if($coupon&&$subtotal>=(int)$coupon['min_order'])$discount=$coupon['type']==='percent'?intdiv($subtotal*(int)$coupon['value'],100):min($subtotal,(int)$coupon['value']);else $couponCode=null;}$total=max(0,$subtotal+$shipping-$discount);$number='BL-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$stmt=$pdo->prepare('INSERT INTO orders(order_number,user_id,status,payment_status,subtotal,shipping,discount,coupon_code,total,shipping_address)VALUES(?, ?, "pending", "unpaid", ?, ?, ?, ?, ?, ?)');$stmt->execute([$number,$current['id'],$subtotal,$shipping,$discount,$couponCode,$total,json_encode(array_merge((array)($d['shipping']??[]),['delivery'=>$delivery]),JSON_UNESCAPED_UNICODE)]);$orderId=(int)$pdo->lastInsertId();
            foreach($locked as [$variant,$qty]){$pdo->prepare('INSERT INTO order_items(order_id,product_id,variant_id,sku,unit_price,quantity)VALUES(?,?,?,?,?,?)')->execute([$orderId,$variant['product_id'],$variant['id'],$variant['sku'],$variant['price'],$qty]);$pdo->prepare('UPDATE product_variants SET stock=stock-? WHERE id=?')->execute([$qty,$variant['id']]);$pdo->prepare('INSERT INTO inventory_movements(variant_id,order_id,quantity,type)VALUES(?,?,?,"sale")')->execute([$variant['id'],$orderId,-$qty]);}
            $gateway=new PaymentGateway(paymentConfig());$payment=$gateway->request($total,$config['app_url'].'/api/payment/callback','سفارش '.$number,$number,$current['phone']);$pdo->prepare('INSERT INTO payments(order_id,authority,amount,status)VALUES(?,?,?,"pending")')->execute([$orderId,$payment['authority'],$total]);$paymentId=(int)$pdo->lastInsertId();$pc=paymentConfig();$pdo->prepare('INSERT INTO integration_payments(payment_id,provider,fee_mode) VALUES(?,?,?)')->execute([$paymentId,$pc['driver'],$pc['fee_mode']??'merchant']);$pdo->commit();audit('order_created','order',$orderId,['number'=>$number]);respond(['ok'=>true,'order_number'=>$number,'redirect'=>$payment['redirect']],201);
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($e instanceof DomainException)fail($e->getMessage(),409);throw $e;}
    }
    if($path==='/admin/stats'&&$method==='GET'){
        requireUser('admin');$pdo=db();
        $salesToday=(int)$pdo->query('SELECT COALESCE(SUM(total),0) FROM orders WHERE payment_status="paid" AND created_at>=CURDATE() AND created_at<CURDATE()+INTERVAL 1 DAY')->fetchColumn();
        $salesYesterday=(int)$pdo->query('SELECT COALESCE(SUM(total),0) FROM orders WHERE payment_status="paid" AND created_at>=CURDATE()-INTERVAL 1 DAY AND created_at<CURDATE()')->fetchColumn();
        $newOrders=(int)$pdo->query('SELECT COUNT(*) FROM orders WHERE status IN ("pending","confirmed") AND created_at>=CURDATE() AND created_at<CURDATE()+INTERVAL 1 DAY')->fetchColumn();
        $pendingOrders=(int)$pdo->query('SELECT COUNT(*) FROM orders WHERE status="pending"')->fetchColumn();
        $activeCustomers=(int)$pdo->query('SELECT COUNT(*) FROM users WHERE role="customer" AND active=1')->fetchColumn();
        $allCustomers=(int)$pdo->query('SELECT COUNT(*) FROM users WHERE role="customer"')->fetchColumn();
        $lowStock=(int)$pdo->query('SELECT COUNT(*) FROM product_variants v JOIN products p ON p.id=v.product_id WHERE p.active=1 AND v.stock<=v.low_stock_threshold')->fetchColumn();
        $outOfStock=(int)$pdo->query('SELECT COUNT(*) FROM product_variants v JOIN products p ON p.id=v.product_id WHERE p.active=1 AND v.stock=0')->fetchColumn();
        $salesChange=$salesYesterday>0?(int)round((($salesToday-$salesYesterday)/$salesYesterday)*100):null;
        respond(['ok'=>true,'stats'=>['sales_today'=>$salesToday,'sales_yesterday'=>$salesYesterday,'sales_change_percent'=>$salesChange,'new_orders'=>$newOrders,'pending_orders'=>$pendingOrders,'customers'=>$activeCustomers,'customers_total'=>$allCustomers,'low_stock'=>$lowStock,'out_of_stock'=>$outOfStock,'generated_at'=>date('c')]]);
    }
    if($path==='/admin/dashboard'&&$method==='GET'){
        requireUser('admin');$pdo=db();$days=(int)($_GET['days']??7);$days=$days===30?30:7;$from=date('Y-m-d',strtotime('-'.($days-1).' days'));
        $salesStmt=$pdo->prepare('SELECT DATE(created_at) sale_date,COALESCE(SUM(total),0) amount FROM orders WHERE payment_status="paid" AND created_at>=? GROUP BY DATE(created_at) ORDER BY sale_date');$salesStmt->execute([$from.' 00:00:00']);$salesMap=[];foreach($salesStmt->fetchAll() as $row)$salesMap[$row['sale_date']]=(int)$row['amount'];
        $sales=[];for($i=$days-1;$i>=0;$i--){$date=date('Y-m-d',strtotime('-'.$i.' days'));$sales[]=['date'=>$date,'amount'=>$salesMap[$date]??0];}
        $statusRows=$pdo->query('SELECT status,COUNT(*) count FROM orders WHERE created_at>=CURDATE() AND created_at<CURDATE()+INTERVAL 1 DAY GROUP BY status')->fetchAll();$statusMap=[];foreach($statusRows as $row)$statusMap[$row['status']]=(int)$row['count'];
        $orderFlow=['new'=>($statusMap['pending']??0)+($statusMap['confirmed']??0),'processing'=>$statusMap['processing']??0,'sent'=>($statusMap['sent']??0)+($statusMap['delivered']??0),'cancelled'=>$statusMap['cancelled']??0];$orderFlow['total']=array_sum($orderFlow);
        $recent=$pdo->query('SELECT o.id,o.order_number,o.status,o.payment_status,o.total,o.created_at,u.name customer FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 3')->fetchAll();
        respond(['ok'=>true,'dashboard'=>['period_days'=>$days,'sales'=>$sales,'order_flow'=>$orderFlow,'recent_orders'=>$recent,'generated_at'=>date('c')]]);
    }
    if($path==='/admin/customers'&&$method==='GET'){requireUser('admin');$rows=db()->query('SELECT u.id,u.name,u.phone,u.role,u.active,u.created_at,COUNT(o.id) orders_count,COALESCE(SUM(CASE WHEN o.payment_status="paid" THEN o.total ELSE 0 END),0) total_spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.active=1 GROUP BY u.id ORDER BY u.created_at DESC')->fetchAll();respond(['ok'=>true,'customers'=>$rows]);}
    if(preg_match('#^/admin/users/(\d+)/role$#',$path,$m)&&$method==='PATCH'){requireCsrf();$admin=requireUser('admin');$target=(int)$m[1];$role=(string)(jsonBody()['role']??'');if(!in_array($role,['customer','admin'],true))fail('نقش کاربر معتبر نیست.',422);if($target===(int)$admin['id']&&$role!=='admin')fail('نمی‌توانید دسترسی حساب مدیر فعلی را حذف کنید.',422);$s=db()->prepare('SELECT role FROM users WHERE id=?');$s->execute([$target]);$old=$s->fetchColumn();if($old===false)fail('کاربر پیدا نشد.',404);if($old==='admin'&&$role==='customer'&&(int)db()->query('SELECT COUNT(*) FROM users WHERE role="admin" AND active=1')->fetchColumn()<=1)fail('حداقل یک مدیر فعال باید باقی بماند.',422);db()->prepare('UPDATE users SET role=? WHERE id=?')->execute([$role,$target]);audit('user_role_changed','user',$target,['from'=>$old,'to'=>$role]);respond(['ok'=>true,'role'=>$role]);}
    if($path==='/admin/coupons'&&$method==='GET'){requireUser('admin');respond(['ok'=>true,'coupons'=>db()->query('SELECT * FROM coupons ORDER BY id DESC')->fetchAll()]);}
    if($path==='/admin/coupons'&&$method==='POST'){requireCsrf();requireUser('admin');$d=jsonBody();$code=strtoupper(trim((string)($d['code']??'')));$type=(string)($d['type']??'percent');$value=(int)($d['value']??0);if(!$code||!in_array($type,['percent','fixed'],true)||$value<1)fail('اطلاعات کد تخفیف معتبر نیست.',422);db()->prepare('INSERT INTO coupons(code,type,value,min_order,active,expires_at)VALUES(?,?,?,?,1,?) ON DUPLICATE KEY UPDATE type=VALUES(type),value=VALUES(value),min_order=VALUES(min_order),active=1,expires_at=VALUES(expires_at)')->execute([$code,$type,$value,(int)($d['min_order']??0),$d['expires_at']?:null]);respond(['ok'=>true]);}
    if($path==='/admin/settings'&&$method==='GET'){requireUser('admin');$settings=db()->query('SELECT `key`,`value` FROM settings')->fetchAll(PDO::FETCH_KEY_PAIR);$settings['sms_password_set']=!empty($settings['sms_password']);$settings['payment_merchant_id_set']=!empty($settings['payment_merchant_id']);unset($settings['sms_password'],$settings['payment_merchant_id']);respond(['ok'=>true,'settings'=>$settings]);}
    if($path==='/admin/settings'&&$method==='PATCH'){requireCsrf();requireUser('admin');$d=jsonBody();$allowed=['store_name','support_phone','standard_shipping','express_shipping','return_days','sms_enabled','sms_username','sms_password','sms_sender','sms_body_id','payment_driver','payment_merchant_id','payment_request_url','payment_verify_url'];if(isset($d['payment_driver'])&&!in_array($d['payment_driver'],['sandbox','real'],true))fail('نوع درگاه معتبر نیست.',422);foreach(['payment_request_url','payment_verify_url'] as $url)if(!empty($d[$url])&&!filter_var($d[$url],FILTER_VALIDATE_URL))fail('آدرس سرویس پرداخت معتبر نیست.',422);$s=db()->prepare('INSERT INTO settings(`key`,`value`)VALUES(?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)');foreach($allowed as $key)if(array_key_exists($key,$d)&&(!in_array($key,['sms_password','payment_merchant_id'],true)||trim((string)$d[$key])!==''))$s->execute([$key,(string)$d[$key]]);audit('settings_updated','settings',null,['keys'=>array_values(array_intersect(array_keys($d),$allowed))]);respond(['ok'=>true]);}
    if($path==='/admin/settings/test-sms'&&$method==='POST'){requireCsrf();requireUser('admin');$result=(new SmsGateway(smsConfig()))->credit();respond(['ok'=>true,'message'=>'ارتباط با ملی پیامک برقرار است.','provider'=>$result]);}
    if($path==='/admin/settings/test-payment'&&$method==='POST'){requireCsrf();requireUser('admin');$payment=paymentConfig();if(($payment['driver']??'sandbox')==='sandbox')respond(['ok'=>true,'message'=>'درگاه آزمایشی فعال است.']);if(empty($payment['merchant_id'])||empty($payment['request_url'])||empty($payment['verify_url']))fail('اطلاعات درگاه واقعی کامل نیست.',422);respond(['ok'=>true,'message'=>'تنظیمات درگاه واقعی کامل است.']);}
    if(preg_match('#^/admin/products/(\d+)/images$#',$path,$m)&&$method==='GET'){requireUser('admin');$id=(int)$m[1];$main=db()->prepare('SELECT image_path FROM products WHERE id=?');$main->execute([$id]);$mainPath=$main->fetchColumn();if($mainPath===false)fail('محصول پیدا نشد.',404);$images=db()->prepare('SELECT id,path,sort_order FROM product_images WHERE product_id=? ORDER BY sort_order,id');$images->execute([$id]);respond(['ok'=>true,'main_image'=>$mainPath,'gallery'=>$images->fetchAll()]);}
    if(preg_match('#^/admin/products/(\d+)/images$#',$path,$m)&&$method==='POST'){requireCsrf();requireUser('admin');$pathName=saveProductImage($_FILES['image']??null);if(!$pathName)fail('تصویر انتخاب نشده است.',422);db()->prepare('INSERT INTO product_images(product_id,path,sort_order)VALUES(?,?,?)')->execute([(int)$m[1],$pathName,(int)($_POST['sort_order']??0)]);respond(['ok'=>true,'path'=>$pathName],201);}
    if(preg_match('#^/admin/products/(\d+)/main-image$#',$path,$m)&&$method==='DELETE'){requireCsrf();requireUser('admin');$id=(int)$m[1];$stmt=db()->prepare('SELECT image_path FROM products WHERE id=?');$stmt->execute([$id]);$image=$stmt->fetchColumn();if($image===false)fail('محصول پیدا نشد.',404);db()->prepare('UPDATE products SET image_path=NULL WHERE id=?')->execute([$id]);if($image&&is_file(dirname(__DIR__).'/'.$image))@unlink(dirname(__DIR__).'/'.$image);audit('product_main_image_deleted','product',$id);respond(['ok'=>true]);}
    if(preg_match('#^/admin/images/(\d+)$#',$path,$m)&&$method==='DELETE'){requireCsrf();requireUser('admin');$s=db()->prepare('SELECT path FROM product_images WHERE id=?');$s->execute([(int)$m[1]]);$image=$s->fetchColumn();db()->prepare('DELETE FROM product_images WHERE id=?')->execute([(int)$m[1]]);if($image&&is_file(dirname(__DIR__).'/'.$image))@unlink(dirname(__DIR__).'/'.$image);respond(['ok'=>true]);}
    if(preg_match('#^/admin/products/(\d+)/variants$#',$path,$m)&&$method==='POST'){requireCsrf();requireUser('admin');$d=jsonBody();if(trim((string)($d['sku']??''))===''||(int)($d['price']??0)<1)fail('اطلاعات تنوع معتبر نیست.',422);db()->prepare('INSERT INTO product_variants(product_id,sku,color,size,price,stock)VALUES(?,?,?,?,?,?)')->execute([(int)$m[1],$d['sku'],trim((string)($d['color']??'default')),$d['size']?:null,(int)$d['price'],max(0,(int)($d['stock']??0))]);respond(['ok'=>true,'id'=>(int)db()->lastInsertId()],201);}
    if($path==='/admin/orders'&&$method==='GET'){requireUser('admin');respond(['ok'=>true,'orders'=>db()->query('SELECT o.*,u.name customer FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC')->fetchAll()]);}
    if($path==='/admin/products'&&$method==='GET'){requireUser('admin');$rows=db()->query('SELECT p.id,p.name,p.slug,p.description,p.long_description,p.image_path,CASE WHEN LOWER(p.brand)="noura" THEN "bilumiere" ELSE p.brand END brand,p.category,p.active,MIN(v.id) variant_id,MIN(v.sku) sku,MIN(v.price) price,SUM(v.stock) stock,MIN(v.low_stock_threshold) low_stock_threshold FROM products p LEFT JOIN product_variants v ON v.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY p.created_at DESC')->fetchAll();respond(['ok'=>true,'products'=>$rows]);}
    if($path==='/admin/products'&&$method==='POST'){
        requireCsrf();requireUser('admin');$name=trim((string)($_POST['name']??''));$category=(string)($_POST['category']??'');$price=(int)($_POST['price']??0);$stock=max(0,(int)($_POST['stock']??0));$sku=trim((string)($_POST['sku']??''));if(mb_strlen($name)<2||!in_array($category,['women','men','unisex','niche'],true)||$price<1||$sku==='')fail('اطلاعات محصول کامل نیست.',422);$image=saveProductImage($_FILES['image']??null);$slug='product-'.bin2hex(random_bytes(5));$pdo=db();$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO products(name,slug,description,image_path,category,active)VALUES(?,?,?,?,?,?)')->execute([$name,$slug,trim((string)($_POST['description']??'')),$image,$category,(int)(($_POST['active']??'0')==='1')]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO product_variants(product_id,sku,color,size,price,stock)VALUES(?,?,"default",NULL,?,?)')->execute([$id,$sku,$price,$stock]);$pdo->commit();audit('product_created','product',$id);respond(['ok'=>true,'id'=>$id],201);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    if(preg_match('#^/admin/products/(\d+)$#',$path,$m)&&$method==='POST'){
        requireCsrf();requireUser('admin');$id=(int)$m[1];$name=trim((string)($_POST['name']??''));$category=(string)($_POST['category']??'');$price=(int)($_POST['price']??0);$stock=max(0,(int)($_POST['stock']??0));$sku=trim((string)($_POST['sku']??''));if(mb_strlen($name)<2||!in_array($category,['women','men','unisex','niche'],true)||$price<1||$sku==='')fail('اطلاعات محصول کامل نیست.',422);$image=saveProductImage($_FILES['image']??null);$pdo=db();$pdo->beginTransaction();try{$sql='UPDATE products SET name=?,description=?,category=?,active=?'.($image?',image_path=?':'').' WHERE id=?';$args=[$name,trim((string)($_POST['description']??'')),$category,(int)(($_POST['active']??'0')==='1')];if($image)$args[]=$image;$args[]=$id;$pdo->prepare($sql)->execute($args);$stmt=$pdo->prepare('SELECT id FROM product_variants WHERE product_id=? ORDER BY id LIMIT 1');$stmt->execute([$id]);$variant=$stmt->fetchColumn();if($variant)$pdo->prepare('UPDATE product_variants SET sku=?,price=?,stock=? WHERE id=?')->execute([$sku,$price,$stock,$variant]);else $pdo->prepare('INSERT INTO product_variants(product_id,sku,color,price,stock)VALUES(?, ?, "default", ?, ?)')->execute([$id,$sku,$price,$stock]);$pdo->commit();audit('product_updated','product',$id);respond(['ok'=>true]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    if(preg_match('#^/admin/products/(\d+)/content$#',$path,$m)&&$method==='PATCH'){requireCsrf();requireUser('admin');$content=trim((string)(jsonBody()['long_description']??''));db()->prepare('UPDATE products SET long_description=? WHERE id=?')->execute([$content,(int)$m[1]]);respond(['ok'=>true]);}
    if(preg_match('#^/admin/products/(\d+)$#',$path,$m)&&$method==='DELETE'){requireCsrf();requireUser('admin');$id=(int)$m[1];$pdo=db();$stmt=$pdo->prepare('SELECT image_path FROM products WHERE id=?');$stmt->execute([$id]);$image=$stmt->fetchColumn();if($image===false)fail('محصول پیدا نشد.',404);$used=$pdo->prepare('SELECT COUNT(*) FROM order_items WHERE product_id=?');$used->execute([$id]);if((int)$used->fetchColumn()>0){$pdo->prepare('UPDATE products SET active=0 WHERE id=?')->execute([$id]);audit('product_archived','product',$id);respond(['ok'=>true,'archived'=>true]);}$pdo->prepare('DELETE FROM products WHERE id=?')->execute([$id]);if($image){$file=dirname(__DIR__).'/'.$image;if(is_file($file))@unlink($file);}audit('product_deleted','product',$id);respond(['ok'=>true,'deleted'=>true]);}
    if(preg_match('#^/admin/variants/(\d+)/stock$#',$path,$m)&&$method==='PATCH'){
        requireCsrf();requireUser('admin');$stock=max(0,(int)(jsonBody()['stock']??0));$pdo=db();$pdo->beginTransaction();try{$stmt=$pdo->prepare('SELECT stock FROM product_variants WHERE id=? FOR UPDATE');$stmt->execute([(int)$m[1]]);$old=$stmt->fetchColumn();if($old===false)throw new DomainException('متغیر پیدا نشد.');$pdo->prepare('UPDATE product_variants SET stock=? WHERE id=?')->execute([$stock,(int)$m[1]]);$pdo->prepare('INSERT INTO inventory_movements(variant_id,quantity,type,note)VALUES(?,?,"adjustment","Admin adjustment")')->execute([(int)$m[1],$stock-(int)$old]);$pdo->commit();audit('stock_adjusted','variant',(int)$m[1],['from'=>$old,'to'=>$stock]);respond(['ok'=>true,'stock'=>$stock]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($e instanceof DomainException)fail($e->getMessage(),404);throw $e;}
    }
    if(preg_match('#^/admin/orders/(\d+)/status$#',$path,$m)&&$method==='PATCH'){requireCsrf();requireUser('admin');$status=jsonBody()['status']??'';if(!in_array($status,['pending','confirmed','processing','sent','delivered','cancelled'],true))fail('وضعیت نامعتبر است.',422);db()->prepare('UPDATE orders SET status=? WHERE id=?')->execute([$status,(int)$m[1]]);audit('order_status_changed','order',(int)$m[1],['status'=>$status]);respond(['ok'=>true]);}
    fail('مسیر پیدا نشد.',404);
}catch(Throwable $error){error_log((string)$error);fail($config['app_env']==='development'?$error->getMessage():'خطای داخلی سرور',500);}
